# Throwaway RDS-Postgres scaffold for the destroy-verification workflow.
#
# This stack exists ONLY to exercise terraform-destroy semantics for a
# stateful resource. It is NOT a reference for production RDS — see the
# Phase 8 `rds_cui` module (forthcoming) for that.
#
# Hardening shortcuts taken on purpose:
#   - deletion_protection = false   so destroy is not blocked
#   - skip_final_snapshot = true    so destroy does not require a snapshot name
#   - publicly_accessible = false   (we still don't expose it; it just isn't gated)
#   - master password is generated by terraform; never used (we do not connect)

data "aws_partition" "current" {}
data "aws_availability_zones" "available" {
  state = "available"
}

resource "random_password" "master" {
  length  = 32
  special = false
}

resource "aws_vpc" "this" {
  cidr_block           = var.vpc_cidr
  enable_dns_hostnames = true
  enable_dns_support   = true
  tags                 = merge(var.tags, { Name = "${var.name}-vpc" })
}

resource "aws_subnet" "this" {
  count                   = 2
  vpc_id                  = aws_vpc.this.id
  cidr_block              = cidrsubnet(var.vpc_cidr, 8, count.index)
  availability_zone       = data.aws_availability_zones.available.names[count.index]
  map_public_ip_on_launch = false
  tags                    = merge(var.tags, { Name = "${var.name}-subnet-${count.index}" })
}

resource "aws_db_subnet_group" "this" {
  name       = "${var.name}-sng"
  subnet_ids = aws_subnet.this[*].id
  tags       = var.tags
}

resource "aws_security_group" "this" {
  name        = "${var.name}-sg"
  description = "Verify-destroy throwaway SG for RDS"
  vpc_id      = aws_vpc.this.id
  tags        = var.tags
}

resource "aws_db_instance" "this" {
  identifier              = var.name
  engine                  = "postgres"
  engine_version          = "16"
  instance_class          = "db.t4g.micro"
  allocated_storage       = 20
  storage_type            = "gp3"
  storage_encrypted       = true
  username                = "verifyadmin"
  password                = random_password.master.result
  db_subnet_group_name    = aws_db_subnet_group.this.name
  vpc_security_group_ids  = [aws_security_group.this.id]
  publicly_accessible     = false
  multi_az                = false
  backup_retention_period = 0

  # The two knobs the workflow is verifying:
  deletion_protection = false
  skip_final_snapshot = true

  tags = var.tags

  lifecycle {
    precondition {
      condition     = contains(["aws", "aws-us-gov"], data.aws_partition.current.partition)
      error_message = "RDS-Postgres on db.t4g.micro is verified only for the aws and aws-us-gov partitions."
    }
  }
}

output "db_instance_identifier" {
  value       = aws_db_instance.this.identifier
  description = "Identifier of the throwaway RDS instance the workflow asserts on."
}

output "partition" {
  value       = data.aws_partition.current.partition
  description = "AWS partition the verification ran in."
}
